# üìõ Custom Error Class üìõ

```js 
class HttpError extends Error {
    constructor(response, message = 'HttpError') {
        super(message);
        this.response = response;
    }
}
```

üßê Now, we could use it in this way:

```js
async function getUser(id) {
    const response = await fetch(`https://reqres.in/api/users/${id}`);
    if (!response.ok) {
        throw new HttpError(response)
    }
    return await response.json();
}

getUser('notfound')
    .then(data => console.log(data))
    .catch(error => {
        if (error instanceof HttpError && error.response.status === 404) {
            return console.log('User with id notfound cannot be found');
        }
        throw error;
    });
```

## ‚òïÔ∏è If you liked it, you can invite me for a coffee at:

https://www.buymeacoffee.com/latteandcode